### ISSUE TITLE
Bombs out if image is external

### ISSUE THREAD

**Issue by OwainWilliams** [OwainWilliams/BlogMarkdownParser#6]
Currently, if a image is an external file e.g. giphy.com or something similar, it bombs because downloading from the website isn't allowed - maybe. 

Need to investigate further. Currently breaks on https://www.owain.codes/blog/posts/2020/february/umbraco-mvp-poornima-nayar/

**Comment by louisjacksonrees** [comment]
I don't believe there will be a super easy way around this. It is most probably due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). There is little you can do other than hosting those assets your self, or what I think is the best option: 
Just store the image URLS, you shouldn't need to download them as they will always on that URL regardless of changes to your blog, so there isn't really a need to "migrate" them, you just point to them as you are already.

**Comment by OwainWilliams** [comment]
Thanks @louisjacksonrees  - My plan just now is to skip them from the downloader which seems to be working. I check to see if the path contains http and then skip it. 
Just now I've come across another issues where the parser bombs out at 404 errors, so just dealing with that 👍
